# Generated by Django 3.0.4 on 2022-01-06 02:03

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('myposts', '0002_auto_20220105_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='images/'),
        ),
    ]
