# Generated by Django 3.0.4 on 2022-01-07 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myposts', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='kind',
        ),
    ]
