# Generated by Django 3.0.4 on 2022-01-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myposts', '0009_auto_20220107_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='detail',
            field=models.BooleanField(blank=True, default=True, verbose_name='里親募集'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='アイコン画像'),
        ),
    ]
