# Generated by Django 3.0.4 on 2022-01-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myposts', '0010_auto_20220111_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='detail',
            field=models.BooleanField(default=False, verbose_name='里親募集'),
        ),
    ]
