# Generated by Django 3.0.4 on 2022-01-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myposts', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_post',
            field=models.ManyToManyField(blank=True, to='myposts.Post', verbose_name='お気に入りの投稿'),
        ),
    ]
