# Generated by Django 3.0.4 on 2022-01-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220104_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
