# Generated by Django 3.0.4 on 2022-01-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cat_lover',
            field=models.BooleanField(default=True),
        ),
    ]
